#!/bin/bash

git_branch() {
    # trunk-ignore(shellcheck/SC2312)
    git branch 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/(\1)/'
}

aws_profile() {
    if [[ -n ${AWS_PROFILE} ]]; then
        echo " (${AWS_PROFILE})"
    fi
}

# Set a fancy color prompt with a date/time at the beginning
export PS1='\[\033[01;31m\][\D{%Y-%m-%d} \t]\[\033[00m\] ${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] $(git_branch)$(aws_profile)\n\$ '
